version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    gosec:
      excludes:
        - G104
    misspell:
      locale: US
  exclusions:
    presets:
      - comments
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - gosec
          - unparam

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/moabdelazem/distroless-app

output:
  formats:
    text:
      path: stdout
  sort-order:
    - linter
    - file

run:
  timeout: 5m
  tests: true
